//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingChatbot.TextStorage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Balint\\Source\\Repos\\BotService\\Shared\\text_storage\\default.json")]
        public string TextStorageLocalPath {
            get {
                return ((string)(this["TextStorageLocalPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsingLocal {
            get {
                return ((bool)(this["UsingLocal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bankingchatbotdemo.file.core.windows.net/textstorage/default.json?sv=2017" +
            "-11-09&ss=f&srt=sco&sp=rc&se=2020-11-22T03:54:59Z&st=2018-11-21T19:54:59Z&spr=ht" +
            "tps&sig=ObRtywN56JJATQr1t%2FNlkWyREYAtPDAj6RkqLDs9Ub4%3D")]
        public string TextStorageAzureUri {
            get {
                return ((string)(this["TextStorageAzureUri"]));
            }
        }
    }
}
